apiVersion: v1
appVersion: 0.0.1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: bdd-spring-1583238369
version: 0.0.1
